type: helm
registry: oci://registry-1.docker.io/bitnamicharts/postgresql
version: 13.1.2
name: postgresql
namespace: postgresql
args:
  - --set
  - installCRDs=true
values:
  webhook:
    timeoutSeconds: 4
